apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-master
  namespace: todo-app
data:
  redis.conf: |-
    # Redis configuration file example.
    port 6379
    appendonly yes
    appendfsync everysec
    dir /var/lib/redis